server:
  port: 8081
spring:
  redis:
    host: 121.4.41.89
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
    port: 6379
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/quarkbbs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      min-idle: 2
      max-active: 8
      initial-size: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#mybatisplus
mybatis-plus:
  configuration:
    #
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:com/quark/common/dao/*.xml
  type-aliases-package: com.quark.common.entity
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0
