spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/quarkbbs?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      min-idle: 2
      max-active: 8
      initial-size: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#mybatisplus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:com/quark/common/dao/*.xml
  type-aliases-package: com.quark.common.entity
logging:
  level:
    org.springframework: warn
    com.quark: debug
